### ISSUE TITLE
Why generate_key's default value is True in modify_user() ? 

### ISSUE THREAD

**Issue by dengchj** [UMIACS/rgwadmin#30]
As above, why param generate_key in modify_user(), its default value is True ? 
```python
def modify_user(self, uid, display_name=None, email=None, key_type='s3',
                access_key=None, secret_key=None, user_caps=None,
                generate_key=True, max_buckets=None, suspended=False):
```
I modify a user param every time and not specified generate_key, it will generate a new key pair every time ？May be this is not what the caller wants. Whether False or None default better and more reasonable？

**Comment by liammonahan** [comment]
Hi @dengchj 

Thanks for reporting.  I think you're completely right.  The default doesn't make a lot of sense.  Let me put in a PR to change it.

Thanks,
Liam

**Comment by liammonahan** [comment]
Hi @dengchj 

This was released in https://github.com/UMIACS/rgwadmin/releases/tag/1.3.0

**Comment by dengchj** [comment]
> Hi @dengchj
> 
> This was released in https://github.com/UMIACS/rgwadmin/releases/tag/1.3.0
👍
