### ISSUE TITLE
List the buckets of the specified user 

### ISSUE THREAD

**Issue by dengchj** [UMIACS/rgwadmin#32]
get_buckets() "Returns a list of all buckets in the radosgw". Is there a way to list the buckets of the specified rgw user？its function similar to `radosgw-admin bucket list  --uid=<user>`

**Comment by liammonahan** [comment]
Yep!

```python
rgw.get_bucket(uid='dengchi')
```

will return all the buckets for a given user.

**Comment by dengchj** [comment]
> Yep!
> 
> ```python
> rgw.get_bucket(uid='dengchi')
> ```
> 
> will return all the buckets for a given user.

Thank you，it's works.
