### ISSUE TITLE
create_bucket reports ServerDown on "BucketAlreadyExists" error

### ISSUE THREAD

**Issue by Dorthu** [UMIACS/rgwadmin#33]
If a call to `create_bucket` fails, the response object does not contain JSON and therefore hits [this block](https://github.com/UMIACS/rgwadmin/blob/master/rgwadmin/rgw.py#L113) and raises a `ServerDown`.  This is most easily reproducible by using a duplicate bucket name.

Digging deeper, I believe this is because the `PUT /:bucket` is not part of Ceph's Admin Ops API, and therefore does not support JSON as a response format.  I notice the URL used is [not prefixed with /admin](https://github.com/UMIACS/rgwadmin/blob/master/rgwadmin/rgw.py#L447) as other routes are, and "Create Bucket" isn't a documented Admin Ops endpoint.

I was going to submit a PR to do something with the 409 response code and try to parse the XML enough to provide a real error [somewhere after this block](https://github.com/UMIACS/rgwadmin/blob/master/rgwadmin/rgw.py#L101), but I'm not sure if that would be desirable given this appears to be the only s3 API endpoint that is supported in this library.  Would such a contribution be welcome, or is that more overhead than it's worth for what appears to be a one-off feature?

**Comment by liammonahan** [comment]
@rleimenstoll Does this have any interrelatedness to #27 ?

**Comment by rleimenstoll** [comment]
@liammonahan Yes, I believe so. I think this is the deeper cause to #27. 

I'd probably come down on the side that it's not worth the effort to re-implement a S3 endpoint into a library about the admin ops api, and we should just strip it. Especially with the data interchange format differences noted by @Dorthu and the fact PUT /:bucket, as noted, does not appear in the Ceph documentation for admin ops. I also don't think it appears in the CLI tools.

**Comment by liammonahan** [comment]
👍 +1 to stripping it for consistency.  I had missed the fact up until now that it is not actually an admin op.
