### ISSUE TITLE
Adding sync-stats ability to get_user

### ISSUE THREAD

**Issue by ArpStorm1** [UMIACS/rgwadmin#52]
Hey,
I've noticed that sometimes, using only get_user with stats=True can return incorrect answer.
After some digging I've noticed that it takes some time to the rgw to sync itself with the current usage of users, and even using radosgw-admin you need to add the --sync-stats flag to get correct answer for sure.
Following this https://github.com/ceph/ceph/pull/17589, I've noticed there is a way to run this flag using radosgw API.

I think it can be really useful to add this ability to the get_user function.

**Comment by dyarnell** [comment]
Thanks, I have merged this code.
