### ISSUE TITLE
Placement Tags for Users

### ISSUE THREAD

**Issue by TheMoti** [UMIACS/rgwadmin#64]
Hello UMIACS team,

Recently we had a requirement of adding placement tags to a Ceph user, which we couldn't find the API for. It is by default an empty array in user info, and I presumed it should at least exist in ```modify_user``` but there was no tag parameter handled in the function body. I know that the [admin API doc](http://docs.ceph.com/docs/master/radosgw/adminops/) itself lacks any description for placement-tags parameter, but as you can see [here](https://github.com/ceph/ceph/blob/main/src/rgw/driver/rados/rgw_rest_user.cc#L235) it **is** handled in the rgw API. I tried changing your lib's ```modify_user``` just a little bit so that it adds ``placement-tags="tag1,tag2"`` to [parameters](https://github.com/UMIACS/rgwadmin/blob/master/rgwadmin/rgw.py#L316) variable; It worked just fine and the added tag was visible in user info. I was wondering if you could expand ```modify_user``` parameters so that it accepts ```placement-tags``` as well? I can PR the changes I mentioned above.
If you're not sure about adding a parameter out of the API doc to the library, can you please review our options for this requirement? Assembling a http request directly in the service is the only thing I can think of, and it's a really bad idea.

**Comment by dyarnell** [comment]
Hi,

I think it is reasonable to add this parameter for now as long as the default is to be None/empty.  I think over time Ceph has often had undocumented options in the api that then were broken/removed over time.  As long as we don't impact users that don't explictly set the parameter then it is fine and we will just work it out when/if they break it down the line.

Happy to review and merge a pull request for this.

**Comment by TheMoti** [comment]
> Hi,
> 
> I think it is reasonable to add this parameter for now as long as the default is to be None/empty. I think over time Ceph has often had undocumented options in the api that then were broken/removed over time. As long as we don't impact users that don't explictly set the parameter then it is fine and we will just work it out when/if they break it down the line.
> 
> Happy to review and merge a pull request for this.

Thank you dyarnell. I created the pull request although I wasn't sure about tagging or any api-doc update required. Also the tests did use the previous lib version and not the source code so I commented new parameter tests to be added afterwards. Can you review the PR and tell me what to add/fix?
Many thanks :)

**Comment by dyarnell** [comment]
This was released as part of https://github.com/UMIACS/rgwadmin/releases/tag/2.4.4 and is available on PyPI now.
