### ISSUE TITLE
create_user throws RGWAdminException instead of UserExists

### ISSUE THREAD

**Issue by vergeev** [UMIACS/rgwadmin#66]
Steps to reproduce:
```python
from rgwadmin import RGWAdmin

rgw = RGWAdmin(access_key='XXX', secret_key='XXX', server='obj.example.com')
rgw.create_user(
    uid='liam',
    display_name='Liam Monahan',
    email='liam@umiacs.umd.edu',
    user_caps='usage=read, write; users=read',
    max_buckets=1000)
rgw.create_user(
    uid='liam',
    display_name='Liam Monahan',
    email='liam@umiacs.umd.edu',
    user_caps='usage=read, write; users=read',
    max_buckets=1000)
```

Expected result: the last line throws `rgwadmin.exceptions.UserExists`.

Actual result: the last line throws `rgwadmin.exceptions.RGWAdminException` with `code="UserAlreadyExists"`.

Why I think this is happening: [the docs](https://github.com/ceph/ceph/blob/f747ab3d09546261cac432726ce603cac61a1a59/doc/radosgw/adminops.rst#special-error-responses-4) say the error response is `UserExists`, but [the rgw code](https://github.com/ceph/ceph/blob/f747ab3d09546261cac432726ce603cac61a1a59/src/rgw/rgw_common.cc#L110) actually produces `UserAlreadyExists`.

Solution I propose:
1. Add `UserAlreadyExists` exception, replace with it `UserExists` here: https://github.com/UMIACS/rgwadmin/blob/4f90b6a53d680abd441f52606c2317719d2fe06d/rgwadmin/rgw.py#L131
2. Make `UserExists` an alias of `UserAlreadyExists` in order to maintain backwards compatibility.

Can I go ahead and open a pull request with a fix?

**Comment by dyarnell** [comment]
Hi Pavel,

I think this is reasonable.  The `UserAlreadyExists` goes back at least to the 12.x.x version of Ceph as the exception in the code.  Please provide a pull request and I will be happy to merge.

**Comment by vergeev** [comment]
Here's the PR: https://github.com/UMIACS/rgwadmin/pull/67. Please let me know if you want me to add anything.

**Comment by dyarnell** [comment]
This was released as part of https://github.com/UMIACS/rgwadmin/releases/tag/2.4.4 and is available on PyPI now.
